---
product_name: IntelliJ 平台 SDK
product_version:
product_type: 开发指南

url: https://beansoft.github.io
baseurl: /idea-docs/

description: Documentation for working with and extending the IntelliJ Platform SDK

# This is tag 191.6183 (2019.1)
upsource:
  server: upsource.jetbrains.com
  repo: idea-ce
  commit: 4f9b5f89b2a19ce700b1373a465c16b28ed8ad52

github_repo: beansoft/idea-docs
youtrack_project: IJSDK
